config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper do
    skip_controllers :applications, :authorized_applications
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  namespace :api do
    namespace :v1 do
      namespace :cms do
        resources :materials, only: %i[index show create update destroy]
        resources :metadata, only: %i[index show]
        resources :products, only: %i[create update show]
        resources :validate, only: %i[index]
      end
      namespace :lms do
        resource :browse, only: :create
        resource :view, only: :create
      end
      resources :apidocs, only: %i[index show]
    end
  end

  resources :materials, only: %i[index show]
  resource :shopping_cart, only: %i[destroy show create]
  get :shopping_cart_cancel, to: 'shopping_carts#cancel'
  resource :sessions, only: %i[show]
  root 'materials#index'
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
  acts_as_shopping_cart

  def tax_pct
    0
  end
end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :authenticate_viewer!
  before_action :find_material, only: %i[create destroy]
  before_action :current_session, only: %i[show cancel]

  def create
    current_cart.add(@material, 0) unless current_cart.cart_items.include? @material
    redirect_to :back, notice: 'Successfully added to the cart'
  end

  def show
    @resources = current_cart.shopping_cart_items.with_material
  end

  def cancel
    current_cart.clear
    redirect_to current_session.cancel_url
  end

  def destroy
    current_cart.remove(@material, 1)
    redirect_to shopping_cart_path, alert: 'Item was removed from cart'
  end
end

app/views/shopping_carts/show.html.erb
<div class="container">
  <div class="row">
    <div class="">
      <div class="panel panel-info">
        <div class="panel-heading">
          <div class="panel-title">
            <div class="row">
              <div class="col-xs-6">
                <h5><span class="glyphicon glyphicon-shopping-cart"></span> Shopping Cart</h5>
              </div>
              <div class="col-xs-2 col-xs-offset-4">
                <%= link_to materials_path, class: "btn btn-primary btn-sm btn-block" do %>
                    <span class="glyphicon glyphicon-share-alt"></span> Continue shopping
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-xs-2"></div>
            <div class="col-xs-3 text-left"><strong>Product</strong></div>
            <div class="col-xs-7">
              <div class="col-xs-7"><strong>Description</strong></div>
              <div class=""><strong>Delete</strong></div>
            </div>
          </div>
          <hr/>
        </div>
        <% @resources.map do |item| %>
          <div class="panel-body">
            <div class="row">
              <div class="col-xs-2"><img class="img-responsive" src="<%= item.material.image.url %>">
              </div>
              <div class="col-xs-3">
                <h4 class="product-name"><strong><%= item.material.name %></strong></h4>
              </div>
              <div class="col-xs-7">
                <div class="col-xs-7">
                  <h4><small><%= item.material.description %></small></h4>
                </div>
                <div class="">
                  <%= link_to shopping_cart_path(id: item.material.id), method: :delete, class: "btn btn-link btn-xs" do %>
                      <span class="glyphicon glyphicon-trash"></span>
                  <% end %>
                </div>
              </div>
            </div>
            <hr>
          </div>
        <% end %>
        <div class="panel-footer">
          <div class="row">
            <div class="col-md-2 col-xs-offset-8">
              <%= link_to 'Cancel', shopping_cart_cancel_path, class: "btn btn-danger btn-block" %>
            </div>
            <div class="col-md-2">
              <%= form_tag @current_session.add_resource_callback_url, authenticity_token: false do %>
                  <%= hidden_field_tag :params, @resources.map(&:material).to_json %>
                  <%= submit_tag 'Approve', class: "btn btn-success btn-block" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>