config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper do
    skip_controllers :applications, :authorized_applications
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  namespace :api do
    namespace :v1 do
      namespace :cms do
        resources :materials, only: %i[index show create update destroy]
        resources :metadata, only: %i[index show]
        resources :products, only: %i[create update show]
        resources :validate, only: %i[index]
      end
      namespace :lms do
        resource :browse, only: :create
        resource :view, only: :create
      end
      resources :apidocs, only: %i[index show]
    end
  end

  resources :materials, only: %i[index show]
  resource :shopping_cart, only: %i[destroy show create]
  get :shopping_cart_cancel, to: 'shopping_carts#cancel'
  resource :sessions, only: %i[show]
  root 'materials#index'
end

app/models/material.rb
class Material < ApplicationRecord
  acts_as_taggable_on :tags

  belongs_to :application, class_name: Doorkeeper::Application
  has_many :product_materials, source: :material_id, dependent: :destroy
  has_many :products, through: :product_materials

  has_many :materials_metadata, dependent: :destroy
  has_many :metadata, through: :materials_metadata

  has_many :shopping_cart_items, class_name: 'ShoppingCartItem'

  has_attached_file :image,
    styles: { thumbnail: '150x150#', standard_resolution: '306x306#', low_resolution: '612x612#' }
  validates_attachment :image, content_type: { content_type: ['image/jpeg', 'image/gif', 'image/png'] },
                       size: { less_than: 5.megabytes }

  validates :name, :description, :language, presence: true
  validates :publisher_resource_id, presence: true, uniqueness: true

  scope :by_viewer, (->(city_id, school_id) {
    joins(products: :licenses).where(licenses: { school_id: [nil, school_id], city_id: [nil, city_id] }).distinct
  })

  self.per_page = 100
end

app/controllers/api/v1/cms/materials_controller.rb
module Api
  module V1
    module Cms
      class MaterialsController < ::Api::BaseController
        include MaterialsApiPagination
        before_action :find_material, only: %i[show update destroy]

        def index
          materials = current_application.materials.paginate(page: params[:page])

          if stale?(materials)
            render json: materials, meta: pagination_dict(materials), meta_key: 'pagination'
          end
        end

        def show
          render json: @material, adapter: :attribute if stale?(@material)
        end

        def create
          new_material = current_application.materials.build(create_params)
          new_material.tag_list = params[:tags]

          render json: { success: 1, resource_uid: new_material.publisher_resource_id } if new_material.save!
        end

        def update
          @material.tag_list = params[:tags] if params[:tags].present?

          render json: { success: 1, resource_uid: @material.publisher_resource_id } if @material.update!(create_params)
        end

        def destroy
          @material.destroy!

          render json: { success: 1 }
        end

        private

        def create_params
          params.permit(:name, :description, :language, :publisher_resource_id, :publisher_url, :metadata, :image)
        end
      end
    end
  end
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :authenticate_viewer!, except: :index

  def index
    @materials = Material.by_viewer(current_session.try(:[], :city_id), current_session.try(:[], :school_id))
      .order(id: :asc).paginate(page: params[:page], per_page: 9)
  end

  def show
    @material = Material.by_viewer(current_session[:city_id], current_session[:school_id]).find(params[:id])
  end
end

app/views/materials/index.html.erb
<div class="container">
  <div class="row">
    <% @materials.each_slice(3) do |group| %>
        <% group.each do |material| %>
            <div class="col-md-4">
              <div class="thumbnail">
                <img src="<%= material.image.url(:standard_resolution) %>" />
                <div class="caption text-center">
                  <h3><%= material.name %></h3>
                  <p><%= material.description %></p>
                  <% if user_sign_in? %>
                  <p>
                    <%= link_to 'VIEW DETAILS', material_path(id: material.id, page: params[:page]), class: "btn btn-info", role: "button" %>
                    <%= link_to 'ADD TO CART',shopping_cart_path(id: material.id), method: :post, class: "btn btn-success add-to-cart" %>
                  </p>
                  <% end %>
                </div>
              </div>
            </div>
        <% end %>
    <% end %>
  </div>
  <!-- pagination -->
  <div class="col-md-12 text-center">
    <%= will_paginate @materials, renderer: BootstrapPagination::Rails %>
  </div>
</div>

app/views/materials/show.html.erb
<div class="container">
  <div class="back-material-list">
    <%= link_to materials_path(page: params[:page]), class: 'btn btn-primary' do %>
        <span class="glyphicon glyphicon-share-alt " aria-hidden="true">&nbsp</span>Materials list
    <% end %>
  </div>
  <div class="row table-row">
    <div class="col-md-6">
      <div class="thumbnail">
        <img src="<%= @material.image.url(:standard_resolution) %>" />
      </div>
    </div>
    <div class="col-md-6">
      <div class="row">
        <div class="col-md-12">
          <h1><%= @material.name %></h1>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <p class="description">Description: <%= @material.description %></p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <span>Language: <%= @material.language %></span>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <span>Tags: </span>
          <% @material.tag_list.each do |tag|  %>
            <span class="tag label label-info"><%= tag %></span>
          <% end %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <span>Publisher Data: <%= @material.publisher_data %></span>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <p>Metadata: </p>
          <ul>
            <% @material.metadata.enabled.each do |item| %>
                <li><%= "#{item.country}#{item.subject}" %></li>
            <% end %>
          </ul>
        </div>
      </div>
        <div class="col-md-12">
          <%= link_to 'ADD TO CART', shopping_cart_path(id: @material.id), method: :post, class: "btn btn-success btn-block add-to-cart" %>
        </div>
    </div>
  </div>
</div>